knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: google
