apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-platform.fullname" . }}-client
  labels:
    {{- include "api-platform.labelsclient" . | nindent 4 }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "api-platform.selectorLabelsclient" . | nindent 4 }}
